apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysb-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysb
  template:
    metadata:
      labels:
        app: mysb
    spec:
      containers:
      - name: mysb-pod
        image: 211.183.3.10:5000/mysb:1
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: mysb-svc
spec:
  type: NodePort
  selector:
    app: mysb
  ports:
  - nodePort: 31111
    port: 80
    targetPort: 8085
